name: ci
on:
  pull_request:
  push:
    branches:
      - main
concurrency:
  # Cancels pending runs when a PR gets updated.
  group: ${{ github.head_ref || github.run_id }}-${{ github.actor }}
  cancel-in-progress: true
jobs:
  x86_64-linux-debug:
    timeout-minutes: 420
    runs-on: "ubuntu-latest"
    env:
      zig_version: "0.12.0-dev.1139+4d106076c"
      command: "zig build -Dtarget=x86_64-linux"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: ci/x86_64-linux.sh
  aarch64-linux-debug:
    timeout-minutes: 420
    runs-on: "ubuntu-latest"
    env:
      zig_version: "0.12.0-dev.1139+4d106076c"
      command: "zig build -Dtarget=aarch64-linux"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: ci/x86_64-linux.sh
